### ISSUE TITLE
New Roles

### ISSUE THREAD

**Issue by FallFlatMatt** [BleedingOptimism/AlexTTTIssues#16]
Hitman: https://steamcommunity.com/sharedfiles/filedetails/?id=1403020444
Vampire: https://steamcommunity.com/sharedfiles/filedetails/?id=1361602585
Mesmerist+Thrall: https://steamcommunity.com/sharedfiles/filedetails/?id=2137829511
Amnesiac: https://steamcommunity.com/sharedfiles/filedetails/?id=2001213453
   -maybe make amnesiac take on role from confirmed bodies as well as uncomfirmed

**Comment by BleedingOptimism** [comment]
Done.
Note about amnesiac should be made a new issue if necessary
